name: Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['2.5', '2.6', '2.7']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - run: gem update --remote bundler
      - run: 'gem install bundler:1.17.2'
      - run: bundle install --retry=3
      - run: 'bundle exec rake dummy:prepare'
      - run: bundle exec rspec
