name: Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CODECLIMATE_REPO_TOKEN: 9c938a047651a943393f0f52bfc1d03d71fce0f19bf0f8c1265033af9b09a56e

    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['2.7', '3.0', '3.1']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - run: bundle install --retry=3
      - run: bundle exec rake dummy:prepare
      - run: bundle exec rspec
